
categories = {
    'Filmes': [0, {
        'Terror': [0],
        'Acao': [1],
        'Aventura': [2],
    }],
    'Séries': [1, {}],
    'Shows': [2, {}],
    'Jogos eletrônicos': [3, {}],
    'Jogos de tabuleiro': [4, {}],
    'Jogos de cartas': [5, {}],
    'Livros e Literatura': [6, {
        'Epico': [0],
        'Suspense': [1],
        'Romance': [2],
        'Cientifico': [3]
    }],
    'Beleza e Fitness': [7, {}],
    'Idiomas': [8, {}],
    'Ciência e Ensino (tópicos acadêmicos)': [9, {}],
    'Hardware': [10, {}],
    'Software': [11, {}],
    'Esportes': [12, {}],
    'Dança': [13, {}],
    'Música': [14, {
        'Rock': [0],
        'Pop': [1],
        'Funk': [2],
        'K-pop': [3]
    }],
    'Teatro': [15, {}],
    'Pintura e Desenho': [16, {}],
    'Culinária': [17, {}],
    'Mão na massa (consertos, costura, tricô, etc.)': [18, {}],
    'Casa e Jardim': [19, {}],
    'Pets': [20, {}],
    'Compras': [21, {}],
    'Trabalho voluntário': [22, {}],
    'Política': [23, {}],
    'Finanças': [24, {}],
    'Viagens e Turismo': [25, {}],
    'Intercâmbio': [26, {}],
    'Rolês universitários': [27, {}],
    'Automóveis e Veículos': [28, {}],
    'Esotérico e Holístico': [29, {}],
    'Espiritualidade': [30, {}],
    'Imobiliário': [31, {}],
    'Artesanato': [32, {}],
    'Causas (ambientais, feminismo, vegan...)': [33, {}],
    'Moda': [34, {}],
    'Empreenderismo e Negócios': [35, {}],
    'Fotografia': [36, {}],
    'História': [37, {}],
    'Mitologia': [38, {}],
    'Pessoas e Sociedade': [39, {}],
    'Anime e Mangá': [40, {}],
    'Ficção científica': [41, {}],
    'Fantasia (RPG, senhor dos anéis, etc.)': [42, {}],
    'Ciclismo': [43, {}],
    'Quadrinhos': [44, {}],
    'Saúde': [45, {}]
}
